##############################################################################
###################################WELCOME####################################
##############################################################################
Welcome to the Tonny's ftp service on %L!

There are %N out of %M users logged in.
Your current loginning name is %U.
Your current loginning host name is %R. 
Your current working directory is %C. 

Current system time is %T.
Please send email to %E if there are any problems with this service.
##############################################################################
